##############################
###   Selenium Hub Config  ###
##############################
hub_config:
  hub_url: 'http://selenium_hub_host:4444/wd/hub'
  # Possible options: [WINDOWS|XP|VISTA|MAC|LINUX|UNIX|ANDROID]
  platform: 'LINUX'
  # Possible options: [android|chrome|firefox|htmlunit|internet explorer|iPhone|iPad|opera|safari]
  browserName: 'chrome'
  # Leave EMPTY unless you know the version you need to specify
  version: ''

##############################
###    SauceLabs Config    ###
##############################
sauce_config:
  sauce_user: 'sauce_username'
  sauce_akey: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx'
  # [platform] Possible options
  # PC:[Linux|Windows XP|Windows 7|Windows 8|Windows 8.1|Windows 10]
  # MAC:[OS X 10.8|OS X 10.9|OS X 10.10|OS X 10.11]
  platform: 'OS X 10.10'
  # [browserName] Possible options [internetExplorer|chrome|firefox|opera]
  browserName: 'chrome'
  # [browserVersion] Possible options: https://docs.saucelabs.com/reference/platforms-configurator/#/
  browserVersion: '42.0'
  # [screenResolution] Possible options
  # Windows XP and Windows 7:[800x600|1024x768|1052x864|1152x864|1280x800|1280x960|1280x1024|1400x1050|1440x900|1600x1200|1680x1050|1920x1200|2560x1600]
  # OS X 10.8:[1024x768|1152x864|1152x900|1280x800|1280x1024|1376x1032|1400x1050|1600x1200|1680x1050|1920x1200]
  # Windows 8 and 8.1:[800x600|1024x768|1280x1024]
  # Recommended: 1024x768
  screenResolution: '1024x768'
  # [jobName] Specify ID for the run|build|project
  jobName: 'Test Build 0.1.1'

##############################
###  Browser Stack Config  ###
##############################
browstack_config:
  browstack_user: 'browstack_username'
  browstack_akey: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx'
  # [os] Possible options [WINDOWS|OS X]
  os: 'WINDOWS'
  # [os_ver] Possible options Windows:[XP|7|8|8.1] OS X:[Snow Leopard|Lion|Mountain Lion|Mavericks|Yosemite]
  os_ver: '7'
  # [browser] Possible options [Firefox|Safari|IE|Chrome|Opera]
  browser: 'Firefox'
  # [browser_ver] Options available: https://www.browserstack.com/list-of-browsers-and-platforms?product=automate
  browser_ver: ''
  # [resolution] Possible options
  # Windows(XP,7):[800x600|1024x768|1280x800|1280x1024|1366x768|1440x900|1680x1050|1600x1200|1920x1200|1920x1080|2048x1536]
  # Windows(8,8.1):[1024x768|1280x800|1280x1024|1366x768|1440x900|1680x1050|1600x1200|1920x1200|1920x1080|2048x1536]
  # OS X:[1024x768|1280x960|1280x1024|1600x1200|1920x1080]
  # Default: 1024x768
  resolution: ''
  # [project] A name for a logical group of builds
  project: 'Test Project'
  # [build] A name for a logical group of tests
  build: 'Test Build 0.1.1'
  # [name] An identifier for the test run
  name: 'Test Run 1.0'
  # [debug] Specifies whether you want to generate screenshots or not
  # Possible options [true|false]
  # Default: true
  debug: 'true'
